name: github-actions-ci
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - run: npm install -g bats
      - run: bats -v

      - run: npm ci --ignore-scripts
      - run: npx jest --passWithNoTests --runInBand --no-cache --coverage
